name: MineLC_PvPGames
version: ${project.version}
main: net.minelc.minelc_pvpgames.MineLC_PvPGames
depend: [MineLC_CORE]
authors: [ElBuenAnvita]
description: CORE de PvPGames
website: https://www.minelc.net
